default:
  capital: 10000.0
  commission: 0.0
  initial_time: '2023-01-01T12:00:00+00:00'
  max_position_size: 50000.0
  positions: {}
  sizing_model:
    fraction: .9
    type: FixedFractionalSizing
  slippage: 0.0
