default:
  capital: 100000.0
  commission: 0.0
  initial_time: '2020-01-01T12:00:00+00:00'
  max_position_size: 50000.0
  positions: {}
  sizing_model:
    fraction: 0.1
    type: FixedFractionalSizing
  slippage: 0.0

default0:
  capital: 100000.0
  commission: 0.0
  initial_time: '2025-01-01T12:00:00+00:00'
  max_position_size: 0
  positions: {'SPY':3.2}
  sizing_model:
    fraction: 0.1
    type: FixedFractionalSizing
  slippage: 0.0